[build]
  functions = "functions"  # Directory where your serverless functions are located

[functions]
  node_bundler = "esbuild"  # Optional: specify the bundler (esbuild is recommended)

[[headers]]
  for = "/*"  # Apply headers to all routes
    [headers.values]
      Access-Control-Allow-Origin = "https://soaw.samcart.com"
      Access-Control-Allow-Headers = "Content-Type"
      Access-Control-Allow-Methods = "POST, OPTIONS"
      Access-Control-Allow-Credentials = "true"  # Ensure true is in quotes for proper format
